### ISSUE TITLE
Variant-c(Object Detection)'s label

### ISSUE THREAD

**Issue by wwlaoxi** [mamta-joshi-gehlot/Tomato-Village#2]
Hello, I saw that the labels on the dataset（Variant-c(Object Detection)） are numbers. What is the correspondence between numbers and real tomato disease names, such as 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, which diseases represent respectively?

**Comment by mamta-joshi-gehlot** [comment]
uploaded   . Please check https://github.com/mamta-joshi-gehlot/Tomato-Village/blob/main/Variant-c(Object%20Detection)/Varient-C%20Labels.txt
