### ISSUE TITLE
class names in object detection

### ISSUE THREAD

**Issue by qazalkz** [mamta-joshi-gehlot/Tomato-Village#3]
Hi. In your xml or txt files instead of the name of a class, you just mentioned some numbers: 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0. so what are those? which class?
it would be great if add a labelmap to the repository. thank you in advance.

**Comment by mamta-joshi-gehlot** [comment]
uploaded   . Please check https://github.com/mamta-joshi-gehlot/Tomato-Village/blob/main/Variant-c(Object%20Detection)/Varient-C%20Labels.txt

**Comment by qazalkz** [comment]
thanks
